### PR TITLE
Some edits of README and .bat file, update to v1.3.0

### PR DESCRIPTION
**Pull request by compute-e**
Hello @JoshSCF .
In my fork of this repository, I've edited some things (README.md, code in .bat file,
update to v1.3.0) and would like to add these changes to your JoshScript repository.

Can you read my comments, use the "Files changed" diff
to review changes and merge this pull request please?

### CODE REVIEW

**Comment by user-e** [comment]
@JoshSCF please can you merge this pull request for my small edit (check the file comparison diff).

**Comment by user-e** [comment]
H

**Comment by user-e** [comment]
@JoshSCF you've updated some files here a week ago, so can  
you read my comment above and maybe merge this pull request?

**Comment by user-e** [comment]
@JoshSCF, @ScriptersCFTeam  
Can you read my comment above, review these changes and maybe merge this pull request?
- but don't merge this before I add one more commit to undo the last one (added _by accident_).

**Comment by user-e** [comment]
@JoshSCF, @ScriptersCFTeam  
Can you read my comment above, review these changes and maybe merge this pull request?
 \- but don't merge this before I add one more commit to undo the last one (added _by accident_).

**Comment by compute-e** [comment]
Don't merge this pull request before I add a commit to undo the last one, added by accident.

**Review by compute-e — COMMENTED** [review]
Before writing this, I added that undo commit,  
making this Pull Request ready for you to merge.

**Review by compute-e — COMMENTED** [review]
@JoshSCF this Pull Request is ready for you to merge.

**Comment by user-e** [comment]
Can you reply, @JoshSCF ?

**Comment by compute-e** [comment]
Can you reply, @JoshSCF ?
Read my comments, review changes and merge this pull request, please.

**Review by jotslo — APPROVED** [review]
sorry for the long wait, i don't really look out for pull requests unless someone explicitly directs me to them

**Comment by jotslo** [comment]
oh wow it _has_ been a while, oops

**Comment by compute-e** [comment]
@JoshSCF hello and thanks for merging my work in this PR.

**Pull request merged**
